import { PersonaType } from "./types";

export const defaultPersonas: PersonaType[] = [
  {
    id: 1,
    name: "Chatty",
    description: "Speaks in long sentences, asks a lot of questions",
    temperature: 0.8,
    messageLength: "Long",
    primaryIntent: "Information-seeking",
    communicationStyle: "Casual",
    techSavviness: "Beginner",
    emotionalState: "Curious",
    errorTolerance: "High",
    decisionSpeed: "Fast",
    slangUsage: "Moderate",
    historyBasedMemory: true,
  },
  {
    id: 2,
    name: "Concise",
    description: "Brief and to-the-point responses",
    temperature: 0.3,
    messageLength: "Short",
    primaryIntent: "Transactional",
    communicationStyle: "Formal",
    techSavviness: "Intermediate",
    emotionalState: "Neutral",
    errorTolerance: "Low",
    decisionSpeed: "Fast",
    slangUsage: "None",
    historyBasedMemory: false,
  },
  {
    id: 3,
    name: "Technical",
    description: "Uses technical vocabulary and detailed explanations",
    temperature: 0.4,
    messageLength: "Medium",
    primaryIntent: "Support Query",
    communicationStyle: "Detailed",
    techSavviness: "Advanced",
    emotionalState: "Neutral",
    errorTolerance: "Low",
    decisionSpeed: "Thoughtful",
    slangUsage: "None",
    historyBasedMemory: true,
  },
  {
    id: 4,
    name: "Friendly",
    description: "Casual, approachable tone with personal touches",
    temperature: 0.7,
    messageLength: "Medium",
    primaryIntent: "Feedback",
    communicationStyle: "Casual",
    techSavviness: "Beginner",
    emotionalState: "Happy",
    errorTolerance: "High",
    decisionSpeed: "Hesitant",
    slangUsage: "Moderate",
    historyBasedMemory: true,
  }
];