name: Sync to Enterprise

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'AgentEvaluation/NHD'
    
    steps:
    - name: Checkout Community Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
    - name: Add Enterprise Remote
      env:
        ENTERPRISE_TOKEN: ${{ secrets.ENTERPRISE_SYNC_TOKEN }}
      run: |
        git remote add enterprise https://x-access-token:${ENTERPRISE_TOKEN}@github.com/AgentEvaluation/NotHotDog-enterprise.git
        
    - name: Sync to Enterprise
      run: |
        # Create a sync branch
        git checkout -b sync-from-community-${{ github.sha }}
        
        # Push to enterprise
        git push enterprise sync-from-community-${{ github.sha }}:sync-from-community-${{ github.sha }}
        
    - name: Create Pull Request in Enterprise
      env:
        GITHUB_TOKEN: ${{ secrets.ENTERPRISE_SYNC_TOKEN }}
      run: |
        # Use GitHub CLI to create PR in enterprise repo
        gh pr create \
          --repo AgentEvaluation/NotHotDog-enterprise \
          --base main \
          --head sync-from-community-${{ github.sha }} \
          --title "Sync from Community: ${{ github.event.head_commit.message }}" \
          --body "Automated sync from community repository.
          
          Community commit: ${{ github.sha }}
          Author: ${{ github.event.head_commit.author.name }}
          
          ## Changes
          ${{ github.event.head_commit.message }}
          
          ---
          *This PR was automatically created by the sync workflow.*"